fix: tests failing due to duplicated providermessage. I.e
     resource_kubectl_examples_test.go:40: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: Duplicate provider configuration

          on terraform_plugin_test.tf line 2:
           2: provider "kubectl" {

        A default (non-aliased) provider configuration for "kubectl" was already
        given at terraform_plugin_test.tf:1,1-19. If multiple configurations are
        required, set the "alias" argument for alternative configurations.
    testing_new.go:74: Error retrieving state, there may be dangling resources: exit status 1